#!/usr/bin/env bash

#xrandr --auto --output DP1 --mode 1920x1200 --left-of eDP1 --primary
xrandr --auto --output HDMI1 --mode 2560x1440 --right-of eDP1 --primary
xrandr --auto --output eDP1 --left-of HDMI1

kill $(pgrep stalonetray)
stalonetray -c ~/.xmonad/stalonetrayrc-dual &

feh --bg-scale ~/Downloads/abstract_circles.jpg
