alias ll='ls -lhG'
alias lla='ls -lhaG'

alias ber='bundle exec rake'
alias be='bundle exec'
alias sp='bundle exec rspec'
alias rdb='bundle exec rails dbconsole'
alias rs='bundle exec rails server'
alias rc='bundle exec rails console'
alias r='bundle exec rails'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias svim='sudo vim'
alias lvim='vim -c "normal '\''0"'

alias ..='cd ../'
alias ...='cd ../../'

alias vimod='vim -p $(git diff --name-only | uniq)'

alias dc='docker-compose'
alias de='docker exec -it'

alias tlisten='sudo lsof -iTCP -sTCP:LISTEN -P -n'
alias ulisten='sudo lsof -iUDP -P -n | egrep -v "(127|::1)"'
